#!/usr/bin/env bash
# OPERATION COPPERCLAW — Platform-aware start script
# COSMIC INDIGO // REL KESTREL COALITION // EXERCISE
#
# Detects OS and GPU, writes a compose override, then starts the stack.
# Supported platforms:
#   macOS Apple Silicon  — RamaLama via Metal/MLX
#   macOS Intel          — CPU only (recommend LLM_BACKEND=anthropic)
#   Linux NVIDIA         — CUDA (default compose, no override needed)
#   Linux AMD            — ROCm via /dev/kfd + /dev/dri
#   Linux CPU only       — No GPU (recommend LLM_BACKEND=anthropic)

set -euo pipefail

OVERRIDE_FILE=".compose.platform-override.yml"

# ---------------------------------------------------------------------------
# Detect compose runtime
# ---------------------------------------------------------------------------
if command -v podman-compose &>/dev/null; then
    COMPOSE_CMD="podman-compose"
elif command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
else
    echo "ERROR: No container runtime found."
    echo "       Install Podman (+ podman-compose) or Docker Desktop."
    exit 1
fi

# ---------------------------------------------------------------------------
# Override generators
# ---------------------------------------------------------------------------

override_mac_apple_silicon() {
    cat > "$OVERRIDE_FILE" <<'EOF'
# Auto-generated by start.sh — macOS Apple Silicon
# Clears NVIDIA device reservation; RamaLama detects Metal/MLX automatically.
# Swaps RHEL9 PostgreSQL image for Docker Hub official (ARM64-compatible).
version: "3.8"
services:
  ramalama:
    deploy:
      resources:
        reservations:
          devices: []
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: copperclaw
      POSTGRES_PASSWORD: copperclaw
      POSTGRES_DB: copperclaw
EOF
}

override_mac_intel() {
    cat > "$OVERRIDE_FILE" <<'EOF'
# Auto-generated by start.sh — macOS Intel
# Clears NVIDIA device reservation; RamaLama will run CPU-only (very slow).
# Swaps RHEL9 PostgreSQL image for Docker Hub official.
version: "3.8"
services:
  ramalama:
    deploy:
      resources:
        reservations:
          devices: []
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: copperclaw
      POSTGRES_PASSWORD: copperclaw
      POSTGRES_DB: copperclaw
EOF
}

override_linux_amd() {
    cat > "$OVERRIDE_FILE" <<'EOF'
# Auto-generated by start.sh — Linux AMD GPU (ROCm)
# Clears NVIDIA device reservation; mounts ROCm devices instead.
version: "3.8"
services:
  ramalama:
    deploy:
      resources:
        reservations:
          devices: []
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
EOF
}

override_linux_cpu() {
    cat > "$OVERRIDE_FILE" <<'EOF'
# Auto-generated by start.sh — Linux CPU only
# Clears NVIDIA device reservation; RamaLama will run CPU-only (very slow).
version: "3.8"
services:
  ramalama:
    deploy:
      resources:
        reservations:
          devices: []
EOF
}

# ---------------------------------------------------------------------------
# GPU detection (Linux)
# ---------------------------------------------------------------------------
detect_gpu_linux() {
    if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null 2>&1; then
        echo "nvidia"
    elif command -v rocm-smi &>/dev/null && rocm-smi &>/dev/null 2>&1; then
        echo "amd"
    elif [ -e /dev/kfd ]; then
        echo "amd"
    else
        echo "cpu"
    fi
}

# ---------------------------------------------------------------------------
# Platform detection
# ---------------------------------------------------------------------------
OS=$(uname -s)
ARCH=$(uname -m)
PLATFORM_LABEL=""
USE_OVERRIDE=true

if [ "$OS" = "Darwin" ]; then
    if [ "$ARCH" = "arm64" ]; then
        PLATFORM_LABEL="macOS Apple Silicon (Metal/MLX)"
        override_mac_apple_silicon
    else
        PLATFORM_LABEL="macOS Intel (CPU only)"
        echo ""
        echo "  WARNING: Intel Mac detected."
        echo "           RamaLama will run CPU-only — inference on a 14B model will be"
        echo "           very slow. Set LLM_BACKEND=anthropic in .env for usable performance."
        echo ""
        override_mac_intel
    fi
elif [ "$OS" = "Linux" ]; then
    GPU=$(detect_gpu_linux)
    case "$GPU" in
        nvidia)
            PLATFORM_LABEL="Linux NVIDIA CUDA"
            USE_OVERRIDE=false
            rm -f "$OVERRIDE_FILE"
            ;;
        amd)
            PLATFORM_LABEL="Linux AMD GPU (ROCm)"
            override_linux_amd
            ;;
        cpu)
            PLATFORM_LABEL="Linux CPU only"
            echo ""
            echo "  WARNING: No GPU detected."
            echo "           RamaLama will run CPU-only — inference on a 14B model will be"
            echo "           very slow. Set LLM_BACKEND=anthropic in .env for usable performance."
            echo ""
            override_linux_cpu
            ;;
    esac
else
    echo "ERROR: Unsupported OS: $OS"
    exit 1
fi

# ---------------------------------------------------------------------------
# Bootstrap .env
# ---------------------------------------------------------------------------
if [ ! -f .env ]; then
    cp .env.example .env
    echo "  Created .env from .env.example."
    echo "  Edit .env to configure LLM backend, API keys, and CoT simulation settings."
    echo ""
fi

# ---------------------------------------------------------------------------
# Launch
# ---------------------------------------------------------------------------
COMPOSE_ARGS="-f podman-compose.yml"
if [ "$USE_OVERRIDE" = "true" ] && [ -f "$OVERRIDE_FILE" ]; then
    COMPOSE_ARGS="$COMPOSE_ARGS -f $OVERRIDE_FILE"
fi

echo "  Platform : $PLATFORM_LABEL"
echo "  Runtime  : $COMPOSE_CMD"
echo "  Override : ${USE_OVERRIDE}"
echo ""
echo "Starting COPPERCLAW..."
echo ""

# shellcheck disable=SC2086
exec $COMPOSE_CMD $COMPOSE_ARGS up "$@"
